### PR TITLE
Adding flag_low_counts

### PR DESCRIPTION
**Pull request by thibautjombart**
This PR includes tests and documentation with an example. The new test pass but older tests seem to be failing atm. I did not test the multiple counts case - maybe worth waiting on https://github.com/reconhub/incidence2/issues/57 ? Otherwise I can find another dataset with pre-calculated counts to use in the tests.

### CODE REVIEW

**Comment by thibautjombart** [comment]
Note: this seems to work on the provided examples but fails on other data. Will push updates when I find the origin of the problem and fix it.

**Comment by thibautjombart** [comment]
Added the util `NA_counts_` to address the type matching issue in `dplyr::if_else`. Could also be useful when using NA in vapply.

**Comment by tjtnew** [comment]
LGTM - can you confirm the NA_counts_ function in util was the fix for the problem you found on other data?  If so I'll merge this.

**Comment by thibautjombart** [comment]
> LGTM - can you confirm the NA_counts_ function in util was the fix for the problem you found on other data? If so I'll merge this.

Yes it fixed the issue. I think this can be merged if there are no other issues.

**Pull request merged**
